/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.boilerplate.member.svc.model.impl;

import com.boilerplate.member.svc.model.Member;
import com.boilerplate.member.svc.service.MemberLocalServiceUtil;

/**
 * The extended model base implementation for the Member service. Represents a row in the &quot;Boilerplate_Member&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MemberImpl
 * @see Member
 * @generated
 */
public abstract class MemberBaseImpl extends MemberModelImpl implements Member {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a member model instance should use the <code>Member</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MemberLocalServiceUtil.addMember(this);
		}
		else {
			MemberLocalServiceUtil.updateMember(this);
		}
	}

}