/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.boilerplate.member.svc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Member service. Represents a row in the &quot;Boilerplate_Member&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.boilerplate.member.svc.model.impl.MemberModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.boilerplate.member.svc.model.impl.MemberImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Member
 * @generated
 */
@ProviderType
public interface MemberModel
	extends BaseModel<Member>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a member model instance should use the {@link Member} interface instead.
	 */

	/**
	 * Returns the primary key of this member.
	 *
	 * @return the primary key of this member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this member.
	 *
	 * @param primaryKey the primary key of this member
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this member.
	 *
	 * @return the uuid of this member
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this member.
	 *
	 * @param uuid the uuid of this member
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the member ID of this member.
	 *
	 * @return the member ID of this member
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this member.
	 *
	 * @param memberId the member ID of this member
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the group ID of this member.
	 *
	 * @return the group ID of this member
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this member.
	 *
	 * @param groupId the group ID of this member
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this member.
	 *
	 * @return the company ID of this member
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this member.
	 *
	 * @param companyId the company ID of this member
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the full name of this member.
	 *
	 * @return the full name of this member
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this member.
	 *
	 * @param fullName the full name of this member
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the create date of this member.
	 *
	 * @return the create date of this member
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this member.
	 *
	 * @param createDate the create date of this member
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this member.
	 *
	 * @return the modified date of this member
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this member.
	 *
	 * @param modifiedDate the modified date of this member
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this member.
	 *
	 * @return the field1 of this member
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this member.
	 *
	 * @param field1 the field1 of this member
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this member.
	 *
	 * @return the field2 of this member
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this member is field2.
	 *
	 * @return <code>true</code> if this member is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this member is field2.
	 *
	 * @param field2 the field2 of this member
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this member.
	 *
	 * @return the field3 of this member
	 */
	public int getField3();

	/**
	 * Sets the field3 of this member.
	 *
	 * @param field3 the field3 of this member
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this member.
	 *
	 * @return the field4 of this member
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this member.
	 *
	 * @param field4 the field4 of this member
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this member.
	 *
	 * @return the field5 of this member
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this member.
	 *
	 * @param field5 the field5 of this member
	 */
	public void setField5(String field5);

	@Override
	public Member cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}